### ISSUE TITLE
Run() fails when no schedule is added

### ISSUE THREAD

**Issue by HTechHQ** [vgarvardt/gueron#89]
Hi, I am receiving an error when calling `Run()` before any job has been scheduled / added. See the example below.
As soon as at least one schedule is added before calling `Run()` it all works.

More about my use case: 
A developer in my software should be able to schedule a new cron at any time. 
My approach: Starting the scheduler without any cron and allowing them to be added at any time. To do so, I have a small wrapper around `Add()` that stops and restarts the scheduler, if is was already running.

Desired behavior: the scheduler can start without error even, if nothing is added yet.

Error:  `could not schedule jobs: could not build query to get the list of already scheduled jobs to clean them up: empty slice passed to 'in' query` 

```
func TestGueron(t *testing.T) {
	poolAdapter := pgxv5.NewConnPool(pgHandler.PGx())

	s, err := gueron.NewScheduler(poolAdapter)
	assert.NoError(t, err)

	wm := gue.WorkMap{}

	//s.MustAdd("@every 15m", "log-foo-bar", nil) // <- works if this line is uncommented
	wm["log-foo-bar"] = func(ctx context.Context, j *gue.Job) error {
		fmt.Printf("Working scheduled job: %d\n", j.ID)
		return nil
	}

	ctx, _ := context.WithCancel(context.Background())
	if err := s.Run(ctx, wm, 4); err != nil {
		assert.NoError(t, err)
	}
}
```

Version v2.2.0

**Comment by vgarvardt** [comment]
pls check the version from the `master` solves your problem - made small adjustment at https://github.com/vgarvardt/gueron/pull/90

**Comment by HTechHQ** [comment]
Yes it does. Works perfect for my situation now! 

Thank you a lot!

**Comment by vgarvardt** [comment]
released as https://github.com/vgarvardt/gueron/releases/tag/v2.2.1
